# Generated by Django 4.1.7 on 2023-03-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pyq_year_semester_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='number',
        ),
        migrations.AddField(
            model_name='semester',
            name='sem',
            field=models.CharField(choices=[('semester1', 'semester1'), ('semester2', 'semester2'), ('semester3', 'semester3'), ('semester4', 'semester4'), ('semester5', 'semester5'), ('semester6', 'semester6'), ('semester7', 'semester7')], max_length=50, null=True),
        ),
    ]
