# Generated by Django 4.1.7 on 2023-04-01 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_semester_number_semester_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='course',
        ),
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.course'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='sem',
            field=models.CharField(choices=[('semester1', 'semester1'), ('semester2', 'semester2'), ('semester3', 'semester3'), ('semester4', 'semester4'), ('semester5', 'semester5'), ('semester6', 'semester6'), ('semester7', 'semester7'), ('semester8', 'semester8')], max_length=50, null=True),
        ),
    ]
