# Generated by Django 4.1.7 on 2023-04-02 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_semester_course_link_name_subject_branch_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='BookLink',
        ),
        migrations.RemoveField(
            model_name='pyq',
            name='href',
        ),
        migrations.CreateModel(
            name='PyqLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=500, null=True)),
                ('pyq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.pyq')),
            ],
        ),
    ]
