# Generated by Django 4.1.7 on 2023-04-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_topics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
    ]
