# Generated by Django 4.1.7 on 2023-04-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_vedio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vedio',
            new_name='Video',
        ),
    ]
