# Generated by Django 4.1.7 on 2023-04-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_vedio_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='link',
            new_name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails'),
        ),
    ]
