# Generated by Django 4.1.7 on 2023-04-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyqlink',
            name='month',
            field=models.CharField(choices=[('march', 'march'), ('december', 'december')], max_length=20, null=True),
        ),
    ]
